// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// mbsMvarR
NumericVector mbsMvarR(NumericMatrix x1, NumericVector classes1);
RcppExport SEXP MBS_mbsMvarR(SEXP x1SEXP, SEXP classes1SEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericMatrix >::type x1(x1SEXP );
        Rcpp::traits::input_parameter< NumericVector >::type classes1(classes1SEXP );
        NumericVector __result = mbsMvarR(x1, classes1);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// mbsForwardSelection
NumericVector mbsForwardSelection(NumericMatrix x, NumericVector classes, NumericVector selectedCols, NumericVector selectedRows);
RcppExport SEXP MBS_mbsForwardSelection(SEXP xSEXP, SEXP classesSEXP, SEXP selectedColsSEXP, SEXP selectedRowsSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type classes(classesSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type selectedCols(selectedColsSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type selectedRows(selectedRowsSEXP );
        NumericVector __result = mbsForwardSelection(x, classes, selectedCols, selectedRows);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// mbsBackwardOptimize
NumericVector mbsBackwardOptimize(NumericMatrix x, NumericVector classes, NumericVector selectedCols, NumericVector selectedRows);
RcppExport SEXP MBS_mbsBackwardOptimize(SEXP xSEXP, SEXP classesSEXP, SEXP selectedColsSEXP, SEXP selectedRowsSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type classes(classesSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type selectedCols(selectedColsSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type selectedRows(selectedRowsSEXP );
        NumericVector __result = mbsBackwardOptimize(x, classes, selectedCols, selectedRows);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
