# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mbsMvarR <- function(x1, classes1) {
    .Call('MBS_mbsMvarR', PACKAGE = 'MBS', x1, classes1)
}

mbsForwardSelection <- function(x, classes, selectedCols, selectedRows) {
    .Call('MBS_mbsForwardSelection', PACKAGE = 'MBS', x, classes, selectedCols, selectedRows)
}

mbsBackwardOptimize <- function(x, classes, selectedCols, selectedRows) {
    .Call('MBS_mbsBackwardOptimize', PACKAGE = 'MBS', x, classes, selectedCols, selectedRows)
}

